### ISSUE TITLE
other nova package do not show

### ISSUE THREAD

**Issue by wuxi889** [nemrutco/nova-global-filter#14]
When i insert nova package (ampeco/nova-date-range-filter) into the NovaGlobalFilter, the date range filter do not show.

Maybe you should be compatible with other nova packages.

Translated by Google.  Sry, My English is poor.

**Comment by muzafferdede** [comment]
> This package overwrites Nova's default Metric Cards to allow them to listen "global-filter-changed" event. Make sure there are no any conflicts with other packages.

As i mentioned here, this is expected behaviour since there is no package could be compatible with any custom packages. All we can do is a general use case compatibility as this packages provides already. You are free to make your own package based on this package with fixed compatibility of your used packages.
